SocietyManagementProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from Society import views

from django.urls import path, include
from SocietyManagementApi import views as apiviews
from rest_framework.routers import DefaultRouter


#creatting router object
router=DefaultRouter()
router.register('meetingsapi',apiviews.MeetingsViewSet,basename='meetings')
router.register('vehicle', apiviews.MemberVehicleViewSet, basename='vehicle')
router.register('shares', apiviews.SharesDetailsView, basename='shares')
router.register('househelp', apiviews.HouseHelpView, basename='househelp')
router.register('househelpallocation', apiviews.HouseHelpAllocationView, basename='househelpallocation')
router.register('suggestion', apiviews.suggestionView, basename='suggestion')
router.register('wint-unit', apiviews.UnitWingView, basename='wint_unit')
router.register('attendance', apiviews.AttendanceView, basename='attendance')
router.register('members', apiviews.MemberView, basename='members')


router.register('society-creation', apiviews.SocietyCreationNewView, basename='society_creation')
router.register('society-registration-documents', apiviews.SocietyRegistrationDocumentsView, basename='society_registration_documents')
router.register('bank-creation', apiviews.BankNewView, basename='bank_creation')
router.register('flat-wing', apiviews.FlatWingView, basename='flat_wing')
router.register('society-other-docs', apiviews.SocDocumentNewView, basename='society_other_docs')
router.register('society-required-docs', apiviews.SocietyRegistrationDocumentsView, basename='ssociety_required_docs')
router.register('home-loan', apiviews.HomeLoanDetailsView, basename='home_loan')
router.register('flat-gst', apiviews.GSTDetailsView, basename='flat_gst')
# router.register('members-creation', apiviews.MemberNomineeView, basename='members-creation')

router.register('add-vehicle', apiviews.VehicleView, basename='add_vehicle')










urlpatterns = [
    path('api/',include(router.urls)),

    # path('api/get-soc-id/', apiviews.GetSingleSocView, name='get-soc-id'),
    path('api/getjson/', apiviews.GetSingleSocView, name='getjson'),
    path('api/history/', apiviews.MemberView.as_view({'get': 'member_history_retrieve'}), name='history'),
    path('last-object/', apiviews.get_last_object, name='last-object'),
    path('non-primary/<int:id>/', apiviews.hide_non_primary_member_checkbox, name='non-primary'),
    path('get_ownership/<int:flat_id>/', apiviews.get_ownership, name='get_ownership'),

    




    

    path('admin/', admin.site.urls),
    path('login/', views.login, name="login"),
    path('society-creation/', views.society_creation, name="society_creation"),
    path('house-help-master/', views.house_help_master, name="house_help_master"),
    path('income-expense-ledger/', views.income_expense_ledger, name="income_expense_ledger"),
    path('asset-liability-ledger/', views.asset_liability_ledger, name="asset_liability_ledger"),
    path('extra1/', views.extra1, name="extra1"),
    path('extra2/', views.extra2, name="extra2"),
    path('extra3/', views.extra3, name="extra3"),
    path('society-details-view/', views.society_details_view, name="society_details_view"),
    path('member-master/', views.member_master, name="member_master"),
    path('member-master-creation/', views.member_master_creation, name="member_master_creation"),
    path('member-details-view/', views.member_details_view, name="member_details_view"),
    path('member-edit-view/', views.member_edit_view, name="member_edit_view"),
    path('tenent-master/', views.tenent_master, name="tenent_master"),
    path('tenent-allocation/', views.tenent_allocation, name="tenent_allocation"),
    path('tenant-allocation-edit/', views.tenant_allocation_edit, name="tenant_allocation_edit"),

    path('house-help-master/', views.house_help_master, name="house_help_master"),
    path('house-help-allocation/', views.house_help_allocation, name="house_help_allocation"),
    path('house-help-allocation-edit/', views.house_help_allocation_edit, name="house_help_allocation_edit"),
    path('member-history-view/', views.member_history_view, name="member_history_view"),
    path('ckeditor/', include('ckeditor_uploader.urls')),








]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SocietyManagementApi/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from Society.models import *
from django.core.exceptions import ValidationError
from .models import *




class SocietyCreationNew(models.Model):
    society_name = models.CharField(max_length=200)
    admin_email = models.EmailField(null=True, blank=True)
    alternate_email = models.EmailField(null=True, blank=True)
    admin_mobile_number = models.CharField(max_length=20, null=True, blank=True)
    alternate_mobile_number = models.CharField(max_length=10, null=True, blank=True)
    registration_number = models.CharField(max_length=200, null=True, blank=True)
    registration_doc = models.FileField(upload_to='files/', null=True, blank=True)
    pan_number = models.CharField(max_length=200, null=True, blank=True)
    pan_number_doc = models.FileField(upload_to='files/', null=True, blank=True)
    gst_number = models.CharField(max_length=200, null=True, blank=True)
    gst_number_doc = models.FileField(upload_to='files/', null=True, blank=True)
    interest = models.CharField(max_length=100, null=True, blank=True)
    society_reg_address = models.TextField(null=True, blank=True)
    society_city = models.CharField(max_length=100, null=True, blank=True)
    socity_state = models.CharField(max_length=100, null=True, blank=True)
    pin_code = models.CharField(max_length=100, null=True, blank=True)
    society_corr_reg_address = models.TextField(null=True, blank=True)
    society_corr_city = models.CharField(max_length=100, null=True, blank=True)
    socity_corr_state = models.CharField(max_length=100, null=True, blank=True)
    pin_corr_code = models.CharField(max_length=100, null=True, blank=True)


class Meetings(models.Model):
    date_of_meeting = models.DateField(null=True, blank=True)
    time_of_meeting = models.CharField(max_length=200, null=True, blank=True)
    place_of_meeting = models.CharField(max_length=200, null=True, blank=True)
    agenda =  models.FileField(upload_to='files/', null=True, blank=True)
    financials =  models.FileField(upload_to='files/', null=True, blank=True)
    other =  models.FileField(upload_to='files/', null=True, blank=True)
    content = RichTextUploadingField(default='')


class Suggestion(models.Model):
    meeting = models.ForeignKey(Meetings, on_delete=models.CASCADE)
    suggestions = models.TextField()


class HouseHelp(models.Model):
    # wing_flat = models.ForeignKey(SocietyUnitFlatCreation, on_delete=models.CASCADE)
    house_help_name = models.CharField(max_length=300, error_messages={'blank': 'Name is required!'})
    house_help_pan_number = models.CharField(max_length=300)
    house_help_pan_doc = models.FileField(upload_to='files/')
    house_help_contact = models.CharField(max_length=300)
    house_help_aadhar_number = models.CharField(max_length=300)
    house_help_aadhar_doc = models.FileField(upload_to='files/')
    house_help_address = models.CharField(max_length=300)
    house_help_city = models.CharField(max_length=300)
    house_help_state = models.CharField(max_length=300)
    house_help_pin = models.CharField(max_length=300)
    other_doc = models.FileField(upload_to='files/', null=True, blank=True)
    other_document_specifications = models.CharField(max_length=300, null=True, blank=True)


class HouseHelpAllocationMaster(models.Model):
    wing_flat = models.ForeignKey(SocietyUnitFlatCreation, on_delete=models.CASCADE)
    member_name = models.ForeignKey(MemberMasterCreation, on_delete=models.CASCADE, related_name='owner_allocations_new')
    aadhar_pan = models.ForeignKey(HouseHelp, on_delete=models.CASCADE, related_name='aadhar_pan_allocations_new', blank=True, null=True)
    # pan = models.ForeignKey(HouseHelp, on_delete=models.CASCADE, related_name='pan_allocations_new', blank=True, null=True)
    house_help_name = models.ForeignKey(HouseHelp, on_delete=models.CASCADE, related_name='name_allocations_new')
    role = models.CharField(max_length=300)
    house_help_period_from = models.DateField(blank=True, null=True)
    house_help_period_to = models.DateField(blank=True, null=True)


    # def save(self, *args, **kwargs):
    #     if self.pk is None:  # This is a new instance, i.e., creation
    #         if not self.house_help_period_from:
    #             raise ValidationError("period from date is required.")
    #     else:  # This is an existing instance, i.e., update
    #         if not self.house_help_period_to:
    #             raise ValidationError("period to date is required is required.")
    #     super().save(*args, **kwargs)



# class MemberVehicle(models.Model):
#     wing_flat = models.CharField(max_length=200)
#     parking_lot = models.CharField(max_length=200, null=True, blank=True)
#     vehicle_type = models.CharField(max_length=200, null=True, blank=True)
#     vehicle_number = models.CharField(max_length=200, null=True, blank=True)
#     vehicle_brand = models.CharField(max_length=200, null=True, blank=True)
#     rc_copy = models.CharField(max_length=200, null=True, blank=True)
#     sticker_number = models.CharField(max_length=200, null=True, blank=True)
    

class SocietyBankCreationNew(models.Model):
    society_creation = models.ForeignKey(SocietyCreationNew, on_delete=models.CASCADE)
    beneficiary_name = models.CharField(max_length=100)
    beneficiary_code = models.CharField(max_length=100)
    beneficiary_acc_number = models.CharField(max_length=100)
    beneficiary_bank = models.CharField(max_length=100)
    is_primary = models.BooleanField(default=False, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.society_creation_id:
            print("id=========================")
            # If society_creation is not set, get the last SocietyCreation object
            last_society_creation = SocietyCreationNew.objects.first()
            if last_society_creation:
                self.society_creation = last_society_creation
        super().save(*args, **kwargs)


class FlatWing(models.Model):
    society_creation = models.ForeignKey(SocietyCreationNew, on_delete=models.CASCADE)
    wing = models.CharField(max_length=100)
    flat = models.CharField(max_length=300)
    # wing_flat_unique = models.CharField(max_length=100)

    def save(self, *args, **kwargs):
        if not self.society_creation_id:
            # If society_creation is not set, get the last SocietyCreation object
            last_society_creation = SocietyCreationNew.objects.first()
            if last_society_creation:
                self.society_creation = last_society_creation

        # if self.wing and self.flat:
        #     # Split the flat string into individual flat values
        #     flat_values = self.flat.split(',')

        #     # Loop over each flat value
        #     for flat_value in flat_values:
        #         # Concatenate wing and flat value with a hyphen
        #         wing_flat_unique_value = f"{self.wing}-{flat_value.strip()}"

        #         # Create or update the wing_flat_unique field
        #         if self.wing_flat_unique:
        #             self.wing_flat_unique += f", {wing_flat_unique_value}"
        #         else:
        #             self.wing_flat_unique = wing_flat_unique_value

        # super().save(*args, **kwargs)




class SocietyDocumentCreationNew(models.Model):
    society_creation = models.ForeignKey(SocietyCreationNew, on_delete=models.CASCADE)
    other_document = models.FileField(upload_to='files/')
    other_document_specification = models.CharField(max_length=100)


class SocietyRegistrationDocuments(models.Model):
    society_creation = models.OneToOneField(SocietyCreationNew, on_delete=models.CASCADE)
    completion_cert = models.FileField(upload_to='files/')
    occupancy_cert = models.FileField(upload_to='files/')
    deed_of_conveyance = models.FileField(upload_to='files/')
    society_by_law = models.FileField(upload_to='files/')
    soc_other_document = models.FileField(upload_to='files/', null=True, blank=True)
    soc_other_document_spec = models.CharField(max_length=100, null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.society_creation_id:
            last_society_creation = SocietyCreationNew.objects.first()
            if last_society_creation:
                self.society_creation = last_society_creation

        super().save(*args, **kwargs)




# BELOW BOTH CODE IS NOT UTILIZING
class Members(models.Model):
    wing_flat = models.ForeignKey(SocietyUnitFlatCreation, on_delete=models.CASCADE, verbose_name="Flat No.")
    member_name = models.CharField(max_length=200)
    ownership_percent = models.IntegerField(null=True, blank=True, verbose_name="Ownership %")
    member_position = models.CharField(max_length=200, null=True, blank=True, verbose_name="Position")
    member_dob = models.DateField(null=True, blank=True, verbose_name="DOB")
    member_pan_no = models.CharField(max_length=200, null=True, blank=True, verbose_name="PAN No.")
    member_aadhar_no = models.CharField(max_length=200, null=True, blank=True, verbose_name="Aadhar No.")
    member_address = models.CharField(max_length=200, null=True, blank=True, verbose_name="Address")
    member_state = models.CharField(max_length=200, null=True, blank=True, verbose_name="State")
    member_pin_code = models.CharField(max_length=200, null=True, blank=True, verbose_name="Pin Code")
    member_email = models.EmailField(null=True, blank=True, verbose_name="Email")
    member_contact = models.CharField(max_length=200, null=True, blank=True, verbose_name="Contact No.")
    member_emergency_contact = models.CharField(max_length=200, null=True, blank=True, verbose_name="Emerg. Contact No.")
    member_occupation = models.CharField(max_length=200, null=True, blank=True, verbose_name="Occupation")
    member_is_primary = models.BooleanField(default = False, null=True, blank=True, verbose_name="Primary")

templates/house_help/house_help_modal.html
<form @submit.prevent="submitHouseHelp" enctype="multipart/form-data">
    <div class="row">
        <div class="col-lg-4 mb-3">
            <div class="w-100 sty-input-wrapper">
                <input type="text" class="w-100 sty-inp" v-model="formData.house_help_name" :style="{ borderColor: errors.house_help_name ? 'red' : '' }">
                <label for="id_house_help_name" class="sty-label">House-Help Name</label>
                <span v-if="errors.house_help_name" :style="{ color: errors.house_help_name ? 'red' : 'black' }" class="error">{{ errors.house_help_name[0] }}</span>
                <span v-else></span>
            </div>
        </div>
        <div class="col-lg-8 mb-3">
            <div class="mb-2">

                <div class="input-group">
                    <div class="firstinp w-50 sty-input-wrapper">
                        <input class="w-100 sty-inp" type="text" id="id_house_help_pan_number" v-model="formData.house_help_pan_number">
                        <label for="id_house_help_pan_number" class="sty-label">House-Help PAN No.</label>
                        <span v-if="errors.house_help_pan_number" class="error">{{ errors.house_help_pan_number[0] }}</span>
                        <span v-else></span>
                    </div>
                    <div class="secinp w-50 d-flex">
                        <div class="fileinp">
                            <input type="file" class="sty-inp form-control" style="color: #2b96f1 !important;" ref="house_help_pan_doc" />
                            <span v-if="errors.house_help_pan_doc" class="error">{{ errors.house_help_pan_doc[0] }}</span>
                            <span v-else></span>
                        </div>
                        <div class="prev">
                            <button type="button" class="sty-inp form-control"
                                onclick="PreviewImage('houseHelpPanDoc')">
                                <i class="fa-solid fa-eye" style="color: #2b96f1 !important;"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-4 mb-3">
            <div class="w-100 sty-input-wrapper">
                <input type="number" class="w-100 sty-inp" v-model="formData.house_help_contact" />
                <label for="id_house_help_contact" class="sty-label">House-Help Contact No.</label>
                <span v-if="errors.house_help_contact" class="error">{{ errors.house_help_contact[0] }}</span>
                <span v-else></span>
            </div>
        </div>
        <div class="col-lg-8 mb-3">
            <div class="mb-2">

                <div class="input-group">
                    <div class="firstinp w-50 sty-input-wrapper">
                        <input class="w-100 sty-inp" type="text" v-model="formData.house_help_aadhar_number" />
                        <label for="id_house_help_aadhar_number" class="sty-label">House-Help Aadhaar No.</label>
                        <span v-if="errors.house_help_aadhar_number" class="error">{{ errors.house_help_aadhar_number[0] }}</span>
                        <span v-else></span>
                    </div>
                    <div class="secinp w-50 d-flex">
                        <div class="fileinp">
                            <input type="file" class="sty-inp form-control" style="color: #2b96f1 !important;" ref="house_help_aadhar_doc" />
                            <span v-if="errors.house_help_aadhar_doc" class="error">{{ errors.house_help_aadhar_doc[0] }}</span>
                            <span v-else></span>
                        </div>
                        <div class="prev">
                            <button type="button" class="sty-inp form-control"
                                onclick="PreviewImage('houseHelpAadhaarDoc')">
                                <i class="fa-solid fa-eye" style="color: #2b96f1 !important;"></i>
                            </button>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-12 mb-3">
            <div class="row">
                <div class="col-lg-6  sty-input-wrapper">
                    <textarea class="w-100 sty-inp" cols="30" rows="1" v-model="formData.house_help_address"></textarea>
                    <label for="id_house_help_address" class="sty-label">House-Help Address</label>
                    <span v-if="errors.house_help_address" class="error">{{ errors.house_help_address[0] }}</span>
                    <span v-else></span>
                </div>
                <div class="col-lg-2 sty-input-wrapper">
                    <input type="text" class=" w-100 sty-inp" v-model="formData.house_help_city" />
                    <label for="id_house_help_city" class="sty-label">City</label>
                    <span v-if="errors.house_help_city" class="error">{{ errors.house_help_city[0] }}</span>
                    <span v-else></span>
                </div>
                <div class="col-lg-2 sty-input-wrapper">
                    <select class="w-100 sty-inp form-control" v-model="formData.house_help_state">
                        <option value="#">Select State</option>
                        <option value="Andhra Pradesh">Andhra Pradesh</option>
                        <option value="Arunachal Pradesh">Arunachal Pradesh</option>
                        <option value="Assam">Assam</option>
                        <option value="Bihar">Bihar</option>
                        <option value="Chhattisgarh">Chhattisgarh</option>
                        <option value="Goa">Goa</option>
                        <option value="Gujarat">Gujarat</option>
                        <option value="Haryana">Haryana</option>
                        <option value="Himachal Pradesh">Himachal Pradesh</option>
                        <option value="Jammu and Kashmir">Jammu and Kashmir</option>
                        <option value="Jharkhand">Jharkhand</option>
                        <option value="Karnataka">Karnataka</option>
                        <option value="Kerala">Kerala</option>
                        <option value="Madhya Pradesh">Madhya Pradesh</option>
                        <option value="Maharashtra">Maharashtra</option>
                        <option value="Manipur">Manipur</option>
                        <option value="Meghalaya">Meghalaya</option>
                        <option value="Mizoram">Mizoram</option>
                        <option value="Nagaland">Nagaland</option>
                        <option value="Odisha">Odisha</option>
                        <option value="Punjab">Punjab</option>
                        <option value="Rajasthan">Rajasthan</option>
                        <option value="Sikkim">Sikkim</option>
                        <option value="Tamil Nadu">Tamil Nadu</option>
                        <option value="Telangana">Telangana</option>
                        <option value="Tripura">Tripura</option>
                        <option value="Uttar Pradesh">Uttar Pradesh</option>
                        <option value="Uttarakhand">Uttarakhand</option>
                        <option value="West Bengal">West Bengal</option>
                        <option value="Andaman and Nicobar ">Andaman and Nicobar </option>
                        <option value="Islands">Islands</option>
                        <option value="Dadra and Nagar Haveli">Dadra and Nagar Haveli</option>
                        <option value="Daman and Diu">Daman and Diu</option>
                        <option value="Delhi">Delhi</option>
                        <option value="Ladakh">Ladakh</option>
                        <option value="Lakshadweep">Lakshadweep</option>
                        <option value="Puducherry">Puducherry</option>
                    </select>
                    <label for="id_house_help_state" class="sty-label">State</label>
                    <span v-if="errors.house_help_state" class="error">{{ errors.house_help_state[0] }}</span>
                    <span v-else></span>
                </div>
                <div class="col-lg-2 sty-input-wrapper">
                    <input type="number" class="w-100 sty-inp" v-model="formData.house_help_pin" />
                    <label for="id_house_help_pin" class="sty-label">Pin Code</label>
                    <span v-if="errors.house_help_pin" class="error">{{ errors.house_help_pin[0] }}</span>
                    <span v-else></span>
                </div>
            </div>
        </div>
        <div class="col-lg-6 mb-3 d-flex">
            <div class="w-100 sty-input-wrapper">
                <input type="file" class="w-100 sty-inp form-control" ref="other_doc" />
                <label for="id_other_doc" class="sty-label">Other Documents</label>
                <span v-if="errors.other_doc" class="error">{{ errors.other_doc[0] }}</span>
                <span v-else></span>
            </div>
            <div class="w-100 sty-input-wrapper">
                <input type="text" class="w-100 sty-inp" v-model="formData.other_document_specifications" />
                <label for="id_document_specifications" class="sty-label">Specify your Document</label>
                <span v-if="errors.other_document_specifications" class="error">{{ errors.other_document_specifications[0] }}</span>
                <span v-else></span>
            </div>
            <div class="prev">
                <button type="button" class="sty-inp form-control"
                    onclick="PreviewImage('houseHelpOtherDoc')">
                    <i class="fa-solid fa-eye" style="color: #2b96f1 !important;"></i>
                </button>
            </div>
        </div>
    </div>
    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary" value="Submit" >Save changes</button>
    </div>
</form>